
package at.finpac14;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;


public class AVGUI extends javax.swing.JFrame
{

    /**
     * Creates new form AnlagenverzeichnisGUI
     */
    AVModel model = new AVModel();
    
    
    public AVGUI()
    {
        initComponents();
        onYears();
        tbAnlagenv.setModel(model);
        try
        {
            model.load();
        } catch (IOException ex)
        {
            Logger.getLogger(AVGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex)
        {
            Logger.getLogger(AVGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void onYears()
    {
        ArrayList<String> years_tmp = new ArrayList<String>();
        for (int years = 2005; years <= Calendar.getInstance().get(Calendar.YEAR); years++) {
            years_tmp.add(years + "");
        }
        cbYears.setModel(new DefaultComboBoxModel(years_tmp.toArray()));
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbAnlagenv = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbYears = new javax.swing.JComboBox<>();
        btUpdate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exercise_204_Anlagenverzeichnis");
        setPreferredSize(new java.awt.Dimension(600, 300));

        tbAnlagenv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbAnlagenv);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel1.setLayout(new java.awt.GridLayout(1, 6));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jahr");
        jPanel1.add(jLabel1);

        cbYears.setMaximumRowCount(6);
        jPanel1.add(cbYears);

        btUpdate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btUpdate.setText("Update Table");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onUpdateTable(evt);
            }
        });
        jPanel1.add(btUpdate);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onUpdateTable(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onUpdateTable
        int year = Integer.parseInt((String) cbYears.getSelectedItem());
        for (Anlagenverzeichnis liste : model.getListe()) 
        {
            String yearsOfInbetiebnahme =  liste.getInbetriebnahme();
            String[] tokenbyYear = yearsOfInbetiebnahme.split(",");
            int yearOfCreation = Integer.parseInt(tokenbyYear[0]);
            if(year - yearOfCreation >= 0)
            {
                if(yearsOfInbetiebnahme.contains(","))
                {
                    liste.setBihNutzungsdauer(liste.getNutzungsdauer() - (liste.getNutzungsdauer() - (year - yearOfCreation))-0.5);
                    System.out.println("true");
                }
                else
                {
                    liste.setBihNutzungsdauer(liste.getNutzungsdauer()- (liste.getNutzungsdauer() - (year - yearOfCreation)));
                    System.out.println("false");
                }
            }
            if(liste.getBihNutzungsdauer() != 0)
            {
                double bishafa = liste.getAnschaffungswert()/liste.getNutzungsdauer();
                liste.setAfABisher(bishafa * liste.getBihNutzungsdauer());
                liste.setAfAdJ(bishafa);
                liste.setWertVorAfA(liste.getAnschaffungswert()-liste.getAfABisher());
                liste.setBuchwert(liste.getWertVorAfA()-liste.getAfAdJ());
            }
            repaint();       
        }
    }//GEN-LAST:event_onUpdateTable

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AVGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btUpdate;
    private javax.swing.JComboBox<String> cbYears;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAnlagenv;
    // End of variables declaration//GEN-END:variables
}
